# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"importPDFs": "00_pdf_core.ipynb"}

modules = ["pdf_core.py"]

doc_url = "https://fabraz.github.io/fastagger/"

git_url = "https://github.com/fabraz/fastagger/tree/master/"

def custom_doc_links(name): return None
