# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"AlreadyImportedError": "00_core.ipynb",
         "InvalidFilePath": "00_core.ipynb",
         "InvalidFolderPath": "00_core.ipynb",
         "InvalidFileExtension": "00_core.ipynb",
         "Pdf": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://fabraz.github.io/fastagger/"

git_url = "https://github.com/fabraz/fastagger/tree/master/"

def custom_doc_links(name): return None
