# AUTOGENERATED! DO NOT EDIT! File to edit: 00_pdf_core.ipynb (unless otherwise specified).

__all__ = ['importPDFs']

# Cell
def importPDFs(path, outputFolder, dpi=200, grayscale=True, size=(600, 846)):
    """imports pdf pages to folder
    path: string path for the file or folder
    recursive: boolean choice for traversing the path folder searching for pdf files
    outputFolder: pages image folder destiny
    dpi: image quality, default 200
    grayscale: filter to grayscale, default True
    size: page image size, default (600, 846)
    """
    if checkPath(path) == 'folder':
        for root, d_names, f_names in os.walk(path):
            for f in f_names:
                if f.endswith('.pdf'):
                    try:
                        importPDF(os.path.join(root, f), outputFolder, dpi, grayscale, size)
                    except AlreadyImportedError as e:
                        print(e)